name: touristoo
description: Touristoo 3D Runner - Flutter версия игры для RuStore
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Game Engine (БЕСПЛАТНО)
  flame: ^1.15.0
  flame_audio: ^2.0.0
  vector_math: ^2.1.4

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API (БЕСПЛАТНО)
  http: ^1.1.0
  dio: ^5.4.0

  # Local Storage (БЕСПЛАТНО)
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # VK Cloud (РОССИЙСКИЙ - БЕСПЛАТНО) - заглушки
  # vk_cloud: ^1.0.0
  # vk_cloud_functions: ^1.0.0
  # vk_cloud_storage: ^1.0.0

  # Yandex Ads (РОССИЙСКИЙ - УЖЕ НАСТРОЕН) - заглушка
  # yandex_mobile_ads: ^4.4.0

  # VK Ads (РОССИЙСКИЙ - БЕСПЛАТНО) - заглушка
  # vk_ads: ^1.0.0

  # In-App Purchases (30% комиссия) - заглушка
  # in_app_purchase: ^3.1.11

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0

  # Audio (БЕСПЛАТНО)
  audioplayers: ^5.2.1

  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/characters/
    - assets/images/enemies/
    - assets/images/ui/
    - assets/images/backgrounds/
    - assets/sounds/
    - assets/animations/
